// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:sakina/features/saved/data/models/saved_ayah_model.dart';
import 'package:sakina/features/saved/data/models/saved_hadith_model.dart';
import 'package:sakina/features/saved/data/models/saved_surah_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SavedAyahModelAdapter());
    registerAdapter(SavedHadithModelAdapter());
    registerAdapter(SavedSurahModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SavedAyahModelAdapter());
    registerAdapter(SavedHadithModelAdapter());
    registerAdapter(SavedSurahModelAdapter());
  }
}
